[providers]
node = "18"

[phases.setup]
cmds = ["cd backend"]

[phases.install]
cmds = ["cd backend && npm ci"]

[phases.build]
cmds = ["cd backend && npm run build"]

[phases.start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"